import mongoose from 'mongoose';

const DfmExceptionSchema = new mongoose.Schema(
  {
    code: { type: String, trim: true },
    description: { type: String, trim: true },
    severity: {
      type: String,
      enum: ['info', 'low', 'medium', 'high', 'critical'],
      default: 'medium',
      index: true,
    },
    owner: { type: String, trim: true },
    status: {
      type: String,
      enum: ['open', 'acknowledged', 'in_progress', 'resolved'],
      default: 'open',
      index: true,
    },
    actionDue: { type: Date },
    resolvedAt: { type: Date },
    notes: { type: String, trim: true },
  },
  { timestamps: true }
);

const MaterialShortageSchema = new mongoose.Schema(
  {
    itemCode: { type: String, trim: true },
    description: { type: String, trim: true },
    requiredQty: { type: Number, default: 0 },
    availableQty: { type: Number, default: 0 },
    shortageQty: { type: Number, default: 0 },
    status: {
      type: String,
      enum: ['open', 'ordered', 'in_transit', 'received', 'substituted', 'cancelled'],
      default: 'open',
    },
    supplier: { type: String, trim: true },
    eta: { type: Date },
    comment: { type: String, trim: true },
  },
  { _id: false, timestamps: true }
);

const PlanningWindowSchema = new mongoose.Schema(
  {
    workCenter: { type: String, trim: true },
    start: { type: Date },
    end: { type: Date },
    status: {
      type: String,
      enum: ['tentative', 'scheduled', 'in_progress', 'complete', 'hold'],
      default: 'tentative',
    },
  },
  { _id: false }
);

const StationStatusSchema = new mongoose.Schema(
  {
    state: {
      type: String,
      enum: ['pending', 'in_review', 'approved', 'blocked'],
      default: 'pending',
      index: true,
    },
    owner: { type: String, trim: true },
    notes: { type: String, trim: true },
    lastReviewedAt: { type: Date },
    releaseTarget: { type: Date },
    releasedAt: { type: Date },
  },
  { _id: false }
);

const CamStatusSchema = new mongoose.Schema(
  {
    state: {
      type: String,
      enum: ['pending', 'in_review', 'approved', 'blocked'],
      default: 'pending',
      index: true,
    },
    owner: { type: String, trim: true },
    notes: { type: String, trim: true },
    lastReviewedAt: { type: Date },
    releaseTarget: { type: Date },
    releasedAt: { type: Date },
  },
  { _id: false }
);

const MaterialsStatusSchema = new mongoose.Schema(
  {
    ready: { type: Boolean, default: false },
    mrpRun: { type: Date },
    shortageCount: { type: Number, default: 0 },
    shortages: { type: [MaterialShortageSchema], default: [] },
  },
  { _id: false }
);

const JobCardHistorySchema = new mongoose.Schema(
  {
    action: {
      type: String,
      enum: ['created', 'approved', 'rejected', 'updated', 'comment_added'],
      required: true,
    },
    operator: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    operatorName: { type: String, required: true },
    timestamp: { type: Date, default: Date.now },
    notes: { type: String },
    previousStatus: { type: String },
    newStatus: { type: String },
    version: { type: Number, default: 1 },
  },
  { _id: false, timestamps: true }
);

const CamAttachmentSchema = new mongoose.Schema(
  {
    kind: {
      type: String,
      enum: [
        'drill_file',
        'photo_file',
        'film',
        'job_card',
        'gerber',
        'bom',
        'spec',
        'assembly',
        'model',
        'stl',
        'step',
        '3mf',
        'slicing_profile',
        'gcode',
        'print_log',
        'timelapse',
      ],
      required: true,
    },
    category: {
      type: String,
      enum: ['intake', 'nc_drill', 'phototools', '3d_printing'],
      required: true,
    },
    originalName: { type: String, required: true },
    filename: { type: String, required: true },
    mimeType: { type: String, required: true },
    size: { type: Number, required: true },
    url: { type: String, required: true },
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    uploadedAt: { type: Date, default: Date.now },
    description: { type: String },
    // Job card specific fields
    approvalStatus: {
      type: String,
      enum: ['pending', 'approved', 'rejected'],
      default: 'pending',
    },
    approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    approvedAt: { type: Date },
    rejectionReason: { type: String },
    version: { type: Number, default: 1 },
    parentJobCard: { type: mongoose.Schema.Types.ObjectId }, // Reference to original job card for versioning
    history: { type: [JobCardHistorySchema], default: [] },
    camNumber: { type: String, trim: true }, // CAM number assigned to this attachment
  },
  { _id: false }
);

const MfgWorkOrderSchema = new mongoose.Schema(
  {
    woNumber: { type: String, required: true, unique: true, uppercase: true, trim: true },
    customer: { type: String, trim: true, index: true },
    product: { type: String, trim: true },
    revision: { type: String, trim: true },
    salesOrder: { type: String, trim: true },
    quoteId: { type: mongoose.Schema.Types.ObjectId, ref: 'Quote' },
    priority: {
      type: String,
      enum: ['low', 'normal', 'high', 'hot'],
      default: 'normal',
      index: true,
    },
    status: {
      type: String,
      enum: [
        'draft',
        'cam',
        'planning',
        'fabrication',
        'drilling',
        'sheet_cutting',
        'cnc_drilling',
        'sanding',
        'brushing',
        'photo_imaging',
        'developer',
        'etching',
        'tin_strip',
        'tin_stripping',
        'solder_mask',
        'surface_finish',
        'legend_print',
        'cnc_routing',
        'v_score',
        'flying_probe',
        'final_qc_pdir',
        '3d_printing_intake',
        '3d_printing_file_prep',
        '3d_printing_slicing',
        '3d_printing_queue',
        '3d_printing_active',
        '3d_printing_post_processing',
        '3d_printing_qc',
        '3d_printing_dispatch',
        'testing',
        'packing',
        'dispatch',
        'pth',
        'final_qa',
        'assembly',
        'shipping',
        'shipped',
        'released',
        'in_fab',
        'in_smt',
        'hold',
        'complete',
      ],
      default: 'cam',
      index: true,
    },
  stage: {
      type: String,
      enum: [
        'cam',
        'planning',
        'fabrication',
        'drilling',
        'sheet_cutting',
        'cnc_drilling',
        'sanding',
        'brushing',
        'photo_imaging',
        'developer',
        'etching',
        'tin_strip',
        'tin_stripping',
        'solder_mask',
        'surface_finish',
        'legend_print',
        'cnc_routing',
        'v_score',
        'flying_probe',
    'final_qc_pdir',
    '3d_printing_intake',
    '3d_printing_file_prep',
    '3d_printing_slicing',
    '3d_printing_queue',
    '3d_printing_active',
    '3d_printing_post_processing',
    '3d_printing_qc',
    '3d_printing_dispatch',
    'packing',
    'dispatch',
    'pth',
    'final_qa',
    'assembly',
    'shipping',
    'shipped',
      ],
      default: 'cam',
      index: true,
    },
    travelerVersion: { type: String, trim: true },
    travelerReady: { type: Boolean, default: false },
    mfgApproved: { type: Boolean, default: false },
    quantity: { type: Number, default: 0 },
    planner: { type: String, trim: true },
    camOwner: { type: String, trim: true },
    plannedStart: { type: Date },
    dueDate: { type: Date, index: true },
    camStatus: { type: CamStatusSchema, default: { state: 'pending' } },
    photoImagingStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    photoImagingParams: { type: mongoose.Schema.Types.Mixed },
    photoImagingChecklist: { type: mongoose.Schema.Types.Mixed },
    developerStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    developerParams: { type: mongoose.Schema.Types.Mixed },
    developerChecklist: { type: mongoose.Schema.Types.Mixed },
    etchingStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    etchingParams: { type: mongoose.Schema.Types.Mixed },
    etchingChecklist: { type: mongoose.Schema.Types.Mixed },
    tinStrippingStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    tinStrippingParams: { type: mongoose.Schema.Types.Mixed },
    tinStrippingChecklist: { type: mongoose.Schema.Types.Mixed },
    solderMaskStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    solderMaskParams: { type: mongoose.Schema.Types.Mixed },
    solderMaskChecklist: { type: mongoose.Schema.Types.Mixed },
    surfaceFinishStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    surfaceFinishParams: { type: mongoose.Schema.Types.Mixed },
    surfaceFinishChecklist: { type: mongoose.Schema.Types.Mixed },
    legendPrintingStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    legendPrintingParams: { type: mongoose.Schema.Types.Mixed },
    legendPrintingChecklist: { type: mongoose.Schema.Types.Mixed },
    cncRoutingStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    cncRoutingParams: { type: mongoose.Schema.Types.Mixed },
    cncRoutingChecklist: { type: mongoose.Schema.Types.Mixed },
    vScoringStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    vScoringParams: { type: mongoose.Schema.Types.Mixed },
    vScoringChecklist: { type: mongoose.Schema.Types.Mixed },
    flyingProbeStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    flyingProbeParams: { type: mongoose.Schema.Types.Mixed },
    flyingProbeChecklist: { type: mongoose.Schema.Types.Mixed },
    finalQCPDIRStatus: { type: StationStatusSchema, default: { state: 'pending' } },
    finalQCPDIRParams: { type: mongoose.Schema.Types.Mixed },
    finalQCPDIRChecklist: { type: mongoose.Schema.Types.Mixed },
    packingStatus: { type: StationStatusSchema, default: () => ({}) },
    packingParams: { type: mongoose.Schema.Types.Mixed },
    packingChecklist: { type: mongoose.Schema.Types.Mixed },
    dispatchStatus: { type: StationStatusSchema, default: () => ({}) },
    dispatchParams: { type: mongoose.Schema.Types.Mixed },
    dispatchChecklist: { type: mongoose.Schema.Types.Mixed },
    assemblyStoreStatus: { type: StationStatusSchema, default: () => ({}) },
    assemblyStoreParams: { type: mongoose.Schema.Types.Mixed },
    assemblyStoreChecklist: { type: mongoose.Schema.Types.Mixed },
    stencilStatus: { type: StationStatusSchema, default: () => ({}) },
    stencilParams: { type: mongoose.Schema.Types.Mixed },
    stencilChecklist: { type: mongoose.Schema.Types.Mixed },
    assemblyReflowStatus: { type: StationStatusSchema, default: () => ({}) },
    assemblyReflowParams: { type: mongoose.Schema.Types.Mixed },
    assemblyReflowChecklist: { type: mongoose.Schema.Types.Mixed },
    thSolderingStatus: { type: StationStatusSchema, default: () => ({}) },
    thSolderingParams: { type: mongoose.Schema.Types.Mixed },
    thSolderingChecklist: { type: mongoose.Schema.Types.Mixed },
    visualInspectionStatus: { type: StationStatusSchema, default: () => ({}) },
    visualInspectionParams: { type: mongoose.Schema.Types.Mixed },
    visualInspectionChecklist: { type: mongoose.Schema.Types.Mixed },
    ictStatus: { type: StationStatusSchema, default: () => ({}) },
    ictParams: { type: mongoose.Schema.Types.Mixed },
    ictChecklist: { type: mongoose.Schema.Types.Mixed },
    flashingStatus: { type: StationStatusSchema, default: () => ({}) },
    flashingParams: { type: mongoose.Schema.Types.Mixed },
    flashingChecklist: { type: mongoose.Schema.Types.Mixed },
    functionalTestStatus: { type: StationStatusSchema, default: () => ({}) },
    functionalTestParams: { type: mongoose.Schema.Types.Mixed },
    functionalTestChecklist: { type: mongoose.Schema.Types.Mixed },
    wireHarnessStatus: { type: StationStatusSchema, default: () => ({}) },
    wireHarnessParams: { type: mongoose.Schema.Types.Mixed },
    wireHarnessChecklist: { type: mongoose.Schema.Types.Mixed },
    wireTestingStatus: { type: StationStatusSchema, default: () => ({}) },
    wireTestingParams: { type: mongoose.Schema.Types.Mixed },
    wireTestingChecklist: { type: mongoose.Schema.Types.Mixed },
    threeDPrintingStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingIntakeStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingFilePrepStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingSlicingStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingQueueStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingActiveStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingPostProcessingStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingQcStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingDispatchStatus: { type: StationStatusSchema, default: () => ({}) },
    threeDPrintingParams: { type: mongoose.Schema.Types.Mixed },
    threeDPrintingChecklist: { type: mongoose.Schema.Types.Mixed },
    assembly3DPrintingStatus: { type: StationStatusSchema, default: () => ({}) },
    assembly3DPrintingParams: { type: mongoose.Schema.Types.Mixed },
    assembly3DPrintingChecklist: { type: mongoose.Schema.Types.Mixed },
    assemblyFinalDispatchStatus: { type: StationStatusSchema, default: () => ({}) },
    assemblyFinalDispatchParams: { type: mongoose.Schema.Types.Mixed },
    assemblyFinalDispatchChecklist: { type: mongoose.Schema.Types.Mixed },
    materials: { type: MaterialsStatusSchema, default: () => ({}) },
    planningWindows: { type: [PlanningWindowSchema], default: [] },
    dfmExceptions: { type: [DfmExceptionSchema], default: [] },
    camAttachments: { type: [CamAttachmentSchema], default: [] },
    notes: { type: String, trim: true },
    tags: { type: [String], default: [] },
  },
  { timestamps: true }
);

MfgWorkOrderSchema.index({ woNumber: 1 });
MfgWorkOrderSchema.index({ status: 1, priority: -1 });
MfgWorkOrderSchema.index({ 'camStatus.state': 1 });
MfgWorkOrderSchema.index({ 'materials.ready': 1 });
MfgWorkOrderSchema.index({ dueDate: 1, priority: -1 });

export default mongoose.model('MfgWorkOrder', MfgWorkOrderSchema);
